name: Gradle WebDriver Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: "18"
          distribution: "temurin"

      - name: Start Selenium Docker container
        run: |
          docker run -d --name selenium -p 4444:4444 selenium/standalone-chrome

      - name: Run WebDriver tests with Gradle
        run: |
          ./gradlew clean test -Dselenide.remote=http://localhost:4444/wd/hub

      - name: Stop Selenium Docker container
        run: |
          docker stop selenium
          docker rm selenium