name: Gradle WebDriver Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"

      # Build the Docker image
      - name: Build Docker Image
        run: |
          docker run -d --name selenium -p 4444:4444 selenium/standalone-chrome

      - name: Run WebDriver tests with Gradle
        run: |
          ./gradlew clean test -Dselenide.remote=http://localhost:4444/wd/hub

      - name: Stop Selenium Docker container
        run: |
          docker stop selenium
          docker rm selenium

      - name: Allure History
        uses: actions/checkout@v2
        if: always()
        with:
          ref: gh-pages
          path: gh-pages

      - name: Test marketplace action
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: build/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
          
          
