#name: Java CI with Gradle
#on:
#  pull_request:
#    branches:
#      - '*'
#  push:
#    branches:
#      - 'main'
#
#permissions:
#  contents: read
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    services:
#      selenium:
#        image: selenium/standalone-chrome:110.0
#        options: --shm-size=2gb
#
#    steps:
#      - uses: actions/checkout@v3
#      - name: Set up JDK 18
#        uses: actions/setup-java@v3
#        with:
#          java-version: "18"
#          distribution: "temurin"
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
#      - name: Build with Gradle
#        run: ./gradlew clean test
#
#      - uses: actions/checkout@v2
#      - name: Get Allure history
#        uses: actions/checkout@v2
#        if: always()
#        continue-on-error: true
#        with:
#          ref: gh-pages
#          path: gh-pages
#
#      - name: Allure Report action from marketplace
#        uses: simple-elf/allure-report-action@master
#        if: always()
#        id: allure-report
#        with:
#          allure_results: allure-results
#          gh_pages: gh-pages
#          allure_report: allure-report
#          allure_history: allure-history
#          keep_reports: 20
#
#      - name: Deploy report to Github Pages
#        if: always()
#        uses: peaceiris/actions-gh-pages@v2
#        env:
#          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          PUBLISH_BRANCH: gh-pages
#          PUBLISH_DIR: allure-history
